name: Build Electron App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: x64
          - os: windows-latest
            arch: arm64
          - os: ubuntu-latest
            arch: x64
          - os: macos-latest
            arch: x64
          - os: macos-latest
            arch: arm64
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # Install Linux dependencies
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo dpkg --add-architecture arm64
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libgconf-2-4 libnss3

    - name: Build Electron app
      run: |
        npm run electron:build
      env:
        NODE_ENV: production
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ARCH: ${{ matrix.arch }}
        CSC_IDENTITY_AUTO_DISCOVERY: false
        # This is broken on macOS. Why.
        # See: https://github.com/electron-userland/electron-builder/issues/3179#issuecomment-408347702
        USE_HARD_LINKS: false

    # Windows artifacts
    - name: Upload Windows artifacts
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: windows-{{ matrix.arch }}-installer
        path: |
          dist/*.exe
        if-no-files-found: error

    # macOS artifacts
    - name: Upload macOS artifacts
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v4
      with:
        name: macos-${{ matrix.arch }}-installer
        path: |
          dist/*.dmg
        if-no-files-found: error

    # Linux artifacts
    - name: Upload Linux artifacts
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: linux-{{ matrix.arch }}-installer
        path: |
          dist/*.AppImage
        if-no-files-found: error