name: Build Electron App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # Install Linux dependencies
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libgconf-2-4 libnss3

    - name: Build Electron app
      run: npm run electron:build
      env:
        NODE_ENV: production
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Windows artifacts
    - name: Upload Windows artifacts
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: windows-installer
        path: |
          dist/win-unpacked/**/*
          !dist/win-unpacked/resources/app.asar.unpacked
          dist/*.exe
        if-no-files-found: error

    # macOS artifacts
    - name: Upload macOS artifacts
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v4
      with:
        name: macos-installer
        path: |
          dist/mac-arm64/**/*
          !dist/mac-arm64/resources/app.asar.unpacked
          dist/*.dmg
        if-no-files-found: error

    # Linux artifacts
    - name: Upload Linux artifacts
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: linux-installer
        path: |
          dist/linux-unpacked/**/*
          !dist/linux-unpacked/resources/app.asar.unpacked
          dist/*.AppImage
        if-no-files-found: error