name: Create Draft Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: true
          prerelease: false

      # Download artifacts from the most recent successful build on main
      - name: Download Windows x64 Artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: windows-x64-installer
          workflow: build.yml
          branch: main
          path: artifacts/windows-x64

      - name: Download Windows ARM64 Artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: windows-arm64-installer
          workflow: build.yml
          branch: main
          path: artifacts/windows-arm64

      - name: Download macOS x64 Artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: macos-x64-installer
          workflow: build.yml
          branch: main
          path: artifacts/macos-x64

      - name: Download macOS ARM64 Artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: macos-arm64-installer
          workflow: build.yml
          branch: main
          path: artifacts/macos-arm64

      - name: Download Linux x64 Artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: linux-x64-installer
          workflow: build.yml
          branch: main
          path: artifacts/linux-x64

      - name: Download Linux ARM64 Artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: linux-arm64-installer
          workflow: build.yml
          branch: main
          path: artifacts/linux-arm64

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: |
            artifacts/**/*
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}