name: Create Draft Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: true
          prerelease: false

      - name: Download Windows x64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-x64-installer
          path: artifacts/windows-x64

      - name: Download Windows ARM64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-arm64-installer
          path: artifacts/windows-arm64

      - name: Download macOS x64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-x64-installer
          path: artifacts/macos-x64

      - name: Download macOS ARM64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-arm64-installer
          path: artifacts/macos-arm64

      - name: Download Linux x64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-x64-installer
          path: artifacts/linux-x64

      - name: Download Linux ARM64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-arm64-installer
          path: artifacts/linux-arm64

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for artifact_dir in artifacts/*; do
            for file in "$artifact_dir"/*; do
              if [ -f "$file" ]; then
                platform_arch=$(basename "$artifact_dir")
                filename=$(basename "$file")
                echo "Uploading $filename for $platform_arch"
                gh release upload ${{ github.event.inputs.version }} "$file" --clobber
              fi
            done
          done